steps:
  # Create .env.production from secrets
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cat > .env.production <<EOF
        NEXT_PUBLIC_FIREBASE_API_KEY=$$FIREBASE_API_KEY
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN
        NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID
        NEXT_PUBLIC_FIREBASE_APP_ID=$$FIREBASE_APP_ID
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$$FIREBASE_MEASUREMENT_ID
        NEXT_PUBLIC_API_URL=$$API_URL
        EOF
        cat .env.production
    secretEnv:
      - FIREBASE_API_KEY
      - FIREBASE_AUTH_DOMAIN
      - FIREBASE_PROJECT_ID
      - FIREBASE_STORAGE_BUCKET
      - FIREBASE_MESSAGING_SENDER_ID
      - FIREBASE_APP_ID
      - FIREBASE_MEASUREMENT_ID
      - API_URL

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "bancamia-frontend"
      - "--source=."
      - "--region=southamerica-east1"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--timeout=300"
      - "--memory=1Gi"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
      env: FIREBASE_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
      env: FIREBASE_AUTH_DOMAIN
    - versionName: projects/$PROJECT_ID/secrets/firebase-project-id/versions/latest
      env: FIREBASE_PROJECT_ID
    - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
      env: FIREBASE_STORAGE_BUCKET
    - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
      env: FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
      env: FIREBASE_APP_ID
    - versionName: projects/$PROJECT_ID/secrets/firebase-measurement-id/versions/latest
      env: FIREBASE_MEASUREMENT_ID
    - versionName: projects/$PROJECT_ID/secrets/api-url/versions/latest
      env: API_URL

options:
  logging: CLOUD_LOGGING_ONLY
